base:
  workplace_pvc: resc01-pvc
  working_dir: vq-vae
  random_seed: 42

model:
  input_dims: [32, 32, 3]
  latent_dim: 256
  num_embeddings: 128 
  commitment_loss_factor: 0.25
  quantization_loss_factor: 0.99
  kl_loss_factor: 1.0


volcano:
  job_id: 1
  job_name: cifar10-vq-vae
  min_num_workers: 1
  max_num_workers: 1
  num_gpus_per_worker: 5
  queue: default

train:
  batch_size_per_replica: 512
  epochs: 30
  learning_rate: 3e-4 
  verbosity: 1
