base:
  workplace_pvc: resc01-pvc
  working_dir: vq-vae
  random_seed: 42

model:
  input_dims: [32, 32, 3]
  latent_dim: 8
  num_embeddings: 16 
  commitment_cost_factor: 0.25
  quantization_loss_factor: 0.99
  margin: 50.0
  ham_margin: 20.0
  bernstein_order: 13
  alpha: 0.2

volcano:
  job_id: 1
  job_name: cifar10-vq-vae
  min_num_workers: 1
  max_num_workers: 1
  num_gpus_per_worker: 5
  queue: default

train:
  batch_size_per_replica: 256
  epochs: 30
  learning_rate: 3e-4 
  verbosity: 1
