base:
  workplace_pvc: resc01-pvc
  working_dir: vq-vae
  random_seed: 43

model:
  input_dims: [32, 32, 3]
  latent_dim: 4096
  num_embeddings: 64 
  commitment_cost_factor: 0.25
  quantization_loss_factor: 0.99
  bernstein_order: 13
  alpha: 0.2

volcano:
  job_id: 1
  job_name: cifar10-vq-vae
  min_num_workers: 1
  max_num_workers: 1
  num_gpus_per_worker: 5
  queue: default

train:
  batch_size_per_replica: 512
  epochs: 100
  learning_rate: 3e-4 
  verbosity: 1
